### ISSUE TITLE
Player Updation

### ISSUE THREAD

**Issue by pallavirichhariya22** [blipinsk/ExoPlayer1#1]
Hi,
 Currently i m using your's project with r1.5.12, so i want to update my player to 2.7.0, can you guide me or do you have any sample doc to update the latest one.

**Comment by blipinsk** [comment]
Hello, this library provides just the ability to add Exoplayer1 and Exoplayer2 inside your project. I am not responsible for either of those versions so you will have to look for a migration guide in the official Exoplayer docs: https://google.github.io/ExoPlayer/
