### ISSUE TITLE
version conflicts

### ISSUE THREAD

**Issue by pallavirichhariya22** [blipinsk/ExoPlayer1#2]
Is there any library which will support two  exoplayer versions 2.3.1 , 2.7.0 simultaneously in same project because the library i was using previously was allowing the v1 and v2 simultaneously but now my requirement is for two v2 . can you suggest something that will be very helpful.

**Comment by blipinsk** [comment]
> can you suggest something 

Nah, not really. This is a pretty tricky thing to do as it involves two libraries that use the same, conflicting package name (`com.google.android.exoplayer2`). 
You really have two choices...
1. Create a "library" yourself. Do that by copying the code of the 2.3.1 version and modify the main package to something like e.g. `com.google.android.exoplayer2.pallavirichhariya22`. Export it as `aar` or `jar` and include this file in your the project. Wherever you use 2.3.1 use classes from the new package (`com.google.android.exoplayer2.pallavirichhariya22`).

2. Try to migrate code that uses 2.3.1 to the 2.7.0.

---

Solution 1. will probably be much more labour-intensive and in the future you will probably still have to perform the migration to the newer version. I would suggest going straight for the solution 2., performing all the work in 1. will go to waste in the end.

**Comment by pallavirichhariya22** [comment]
ok thanks
